/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.35
 * Generated at: 2014-08-31 21:27:23 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.header;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class header_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<title>Moderna - Bootstrap 3 flat corporate template</title>\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\r\n");
      out.write("<meta name=\"description\" content=\"\" />\r\n");
      out.write("<meta name=\"author\" content=\"http://bootstraptaste.com\" />\r\n");
      out.write("<!-- css -->\r\n");
      out.write("<link href=\"css/bootstrap.min.css\" rel=\"stylesheet\" />\r\n");
      out.write("<link href=\"css/fancybox/jquery.fancybox.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"css/jcarousel.css\" rel=\"stylesheet\" />\r\n");
      out.write("<link href=\"css/flexslider.css\" rel=\"stylesheet\" />\r\n");
      out.write("<link href=\"css/style.css\" rel=\"stylesheet\" />\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Theme skin -->\r\n");
      out.write("<link href=\"skins/default.css\" rel=\"stylesheet\" />\r\n");
      out.write("\r\n");
      out.write("<!-- HTML5 shim, for IE6-8 support of HTML5 elements -->\r\n");
      out.write("<!--[if lt IE 9]>\r\n");
      out.write("      <script src=\"http://html5shim.googlecode.com/svn/trunk/html5.js\"></script>\r\n");
      out.write("    <![endif]-->\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div id=\"wrapper\">\r\n");
      out.write("\t<!-- start header -->\r\n");
      out.write("<header>\r\n");
      out.write("        <div class=\"navbar navbar-default navbar-static-top\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <div class=\"navbar-header\">\r\n");
      out.write("                    <button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\" data-target=\".navbar-collapse\">\r\n");
      out.write("                        <span class=\"icon-bar\"></span>\r\n");
      out.write("                        <span class=\"icon-bar\"></span>\r\n");
      out.write("                        <span class=\"icon-bar\"></span>\r\n");
      out.write("                    </button>\r\n");
      out.write("                    <a class=\"navbar-brand\" href=\"index.html\">\r\n");
      out.write("\t\t\t\t\t<img src=\"img/logo/logo2.png\"/></a>\r\n");
      out.write("                </div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("                <div class=\"navbar-collapse collapse \">\r\n");
      out.write("                    <ul class=\"nav navbar-nav\">\r\n");
      out.write("                        <li class=\"active\"><a href=\"index.html\">Principal</a></li>\r\n");
      out.write("                        <li class=\"dropdown\">\r\n");
      out.write("                            <a href=\"#\" class=\"dropdown-toggle \" data-toggle=\"dropdown\" data-hover=\"dropdown\" data-delay=\"0\" data-close-others=\"false\">Menu <b class=\" icon-angle-down\"></b></a>\r\n");
      out.write("                            <ul class=\"dropdown-menu\">\r\n");
      out.write("                                <li><a href=\"selecionaProdutos.html\">Rodizio</a></li>\r\n");
      out.write("                                <li><a href=\"selecionaProdutos.html\">À lacarte</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"selecionaProdutos.html\">Bebidas</a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li><a href=\"pricingbox.html\">Lista de Pedidos</a></li>\r\n");
      out.write("                        <li><a href=\"contact.html\">Contato</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\t</header>\r\n");
      out.write("\t<!-- end header -->\r\n");
      out.write("\t<section id=\"featured\">\r\n");
      out.write("\t<!-- start slider -->\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<div class=\"col-lg-12\">\r\n");
      out.write("\t<!-- Slider -->\r\n");
      out.write("        <div id=\"main-slider\" class=\"flexslider\">\r\n");
      out.write("            <ul class=\"slides\">\r\n");
      out.write("              <li>\r\n");
      out.write("                <img src=\"img/slides/1.jpg\" alt=\"\" />\r\n");
      out.write("                <div class=\"flex-caption\">\r\n");
      out.write("                    <h3>Modern Design</h3> \r\n");
      out.write("\t\t\t\t\t<p>Duis fermentum auctor ligula ac malesuada. Mauris et metus odio, in pulvinar urna</p> \r\n");
      out.write("\t\t\t\t\t<a href=\"#\" class=\"btn btn-theme\">Learn More</a>\r\n");
      out.write("                </div>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li>\r\n");
      out.write("                <img src=\"img/slides/2.jpg\" alt=\"\" />\r\n");
      out.write("                <div class=\"flex-caption\">\r\n");
      out.write("                    <h3>Fully Responsive</h3> \r\n");
      out.write("\t\t\t\t\t<p>Sodales neque vitae justo sollicitudin aliquet sit amet diam curabitur sed fermentum.</p> \r\n");
      out.write("\t\t\t\t\t<a href=\"#\" class=\"btn btn-theme\">Learn More</a>\r\n");
      out.write("                </div>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li>\r\n");
      out.write("                <img src=\"img/slides/3.jpg\" alt=\"\" />\r\n");
      out.write("                <div class=\"flex-caption\">\r\n");
      out.write("                    <h3>Clean & Fast</h3> \r\n");
      out.write("\t\t\t\t\t<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit donec mer lacinia.</p> \r\n");
      out.write("\t\t\t\t\t<a href=\"#\" class=\"btn btn-theme\">Learn More</a>\r\n");
      out.write("                </div>\r\n");
      out.write("              </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("\t<!-- end slider -->\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\t\r\n");
      out.write("\t </section>\r\n");
      out.write("\t<section class=\"callaction\">\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<div class=\"col-lg-12\">\r\n");
      out.write("\t\t\t\t<div class=\"big-cta\">\r\n");
      out.write("\t\t\t\t\t<div class=\"cta-text\">\r\n");
      out.write("\t\t\t\t\t\t<h2><span>Faça Seu pedido</span> Nossos Produtos abaixo</h2>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t</section>\r\n");
      out.write("\t\t<!-- javascript\r\n");
      out.write("\t    ================================================== -->\r\n");
      out.write("\t<!-- Placed at the end of the document so the pages load faster -->\r\n");
      out.write("\t<script src=\"js/jquery.js\"></script>\r\n");
      out.write("\t<script src=\"js/jquery.easing.1.3.js\"></script>\r\n");
      out.write("\t<script src=\"js/bootstrap.min.js\"></script>\r\n");
      out.write("\t<script src=\"js/jquery.fancybox.pack.js\"></script>\r\n");
      out.write("\t<script src=\"js/jquery.fancybox-media.js\"></script>\r\n");
      out.write("\t<script src=\"js/google-code-prettify/prettify.js\"></script>\r\n");
      out.write("\t<script src=\"js/portfolio/jquery.quicksand.js\"></script>\r\n");
      out.write("\t<script src=\"js/portfolio/setting.js\"></script>\r\n");
      out.write("\t<script src=\"js/jquery.flexslider.js\"></script>\r\n");
      out.write("\t<script src=\"js/animate.js\"></script>\r\n");
      out.write("\t<script src=\"js/custom.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
