/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.35
 * Generated at: 2014-08-31 21:22:17 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.footer;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class footer_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<title>Footer</title>\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\r\n");
      out.write("<meta name=\"description\" content=\"\" />\r\n");
      out.write("<meta name=\"author\" content=\"http://bootstraptaste.com\" />\r\n");
      out.write("<!-- css -->\r\n");
      out.write("<link href=\"css/bootstrap.min.css\" rel=\"stylesheet\" />\r\n");
      out.write("<link href=\"css/fancybox/jquery.fancybox.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"css/jcarousel.css\" rel=\"stylesheet\" />\r\n");
      out.write("<link href=\"css/flexslider.css\" rel=\"stylesheet\" />\r\n");
      out.write("<link href=\"css/style.css\" rel=\"stylesheet\" />\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Theme skin -->\r\n");
      out.write("<link href=\"skins/default.css\" rel=\"stylesheet\" />\r\n");
      out.write("\r\n");
      out.write("<!-- HTML5 shim, for IE6-8 support of HTML5 elements -->\r\n");
      out.write("<!--[if lt IE 9]>\r\n");
      out.write("      <script src=\"http://html5shim.googlecode.com/svn/trunk/html5.js\"></script>\r\n");
      out.write("    <![endif]-->\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<footer>\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<div class=\"col-lg-3\">\r\n");
      out.write("\t\t\t\t<div class=\"widget\">\r\n");
      out.write("\t\t\t\t\t<h5 class=\"widgetheading\">Get in touch with us</h5>\r\n");
      out.write("\t\t\t\t\t<address>\r\n");
      out.write("\t\t\t\t\t<strong>Moderna company Inc</strong><br>\r\n");
      out.write("\t\t\t\t\t Modernbuilding suite V124, AB 01<br>\r\n");
      out.write("\t\t\t\t\t Someplace 16425 Earth </address>\r\n");
      out.write("\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t<i class=\"icon-phone\"></i> (123) 456-7890 - (123) 555-7891 <br>\r\n");
      out.write("\t\t\t\t\t\t<i class=\"icon-envelope-alt\"></i> email@domainname.com\r\n");
      out.write("\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-lg-3\">\r\n");
      out.write("\t\t\t\t<div class=\"widget\">\r\n");
      out.write("\t\t\t\t\t<h5 class=\"widgetheading\">Pages</h5>\r\n");
      out.write("\t\t\t\t\t<ul class=\"link-list\">\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">Press release</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">Terms and conditions</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">Privacy policy</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">Career center</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">Contact us</a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-lg-3\">\r\n");
      out.write("\t\t\t\t<div class=\"widget\">\r\n");
      out.write("\t\t\t\t\t<h5 class=\"widgetheading\">Latest posts</h5>\r\n");
      out.write("\t\t\t\t\t<ul class=\"link-list\">\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">Lorem ipsum dolor sit amet, consectetur adipiscing elit.</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">Pellentesque et pulvinar enim. Quisque at tempor ligula</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">Natus error sit voluptatem accusantium doloremque</a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-lg-3\">\r\n");
      out.write("\t\t\t\t<div class=\"widget\">\r\n");
      out.write("\t\t\t\t\t<h5 class=\"widgetheading\">Flickr photostream</h5>\r\n");
      out.write("\t\t\t\t\t<div class=\"flickr_badge\">\r\n");
      out.write("\t\t\t\t\t\t<script type=\"text/javascript\" src=\"http://www.flickr.com/badge_code_v2.gne?count=8&amp;display=random&amp;size=s&amp;layout=x&amp;source=user&amp;user=34178660@N03\"></script>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"clear\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div id=\"sub-footer\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"col-lg-6\">\r\n");
      out.write("\t\t\t\t\t<div class=\"copyright\">\r\n");
      out.write("\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t<span>&copy; Moderna 2014 All right reserved. By </span><a href=\"http://bootstraptaste.com\" target=\"_blank\">Bootstraptaste</a>\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-lg-6\">\r\n");
      out.write("\t\t\t\t\t<ul class=\"social-network\">\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\" data-placement=\"top\" title=\"Facebook\"><i class=\"fa fa-facebook\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\" data-placement=\"top\" title=\"Twitter\"><i class=\"fa fa-twitter\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\" data-placement=\"top\" title=\"Linkedin\"><i class=\"fa fa-linkedin\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\" data-placement=\"top\" title=\"Pinterest\"><i class=\"fa fa-pinterest\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\" data-placement=\"top\" title=\"Google plus\"><i class=\"fa fa-google-plus\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t</footer>\r\n");
      out.write("</div>\r\n");
      out.write("<a href=\"#\" class=\"scrollup\"><i class=\"fa fa-angle-up active\"></i></a>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
